OBJS = source/main.cpp source/Environment.cpp source/Functions.cpp source/Object.cpp source/Button.cpp source/Text.cpp

CC = g++

COMPILER_FLAGS = -w -std=c++14

LINKER_FLAGS = -lSDL2 -lSDL2_image -lSDL2_ttf

OBJ_NAME = main

all : $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)

clean:
	rm -rf *.o $(OBJ_NAME)
